/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7159483f-62d9-4254-9cad-442114bfa99e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_sjlTjI3tD",
    "aws_user_pools_web_client_id": "4qj89cfnuc8inj1cjkt378el74",
    "oauth": {}
};


export default awsmobile;
